#### POD config (run one time)
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jdk-mvn-py3-vnc
  labels:
    application: jdk-mvn-py3-vnc
spec:
  # 1 Pods should exist at all times.
  replicas: 1
  template:
    metadata:
      labels:
        application: jdk-mvn-py3-vnc
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: jdk-mvn-py3-vnc
        image: openkbs/jdk-mvn-py3-vnc
        imagePullPolicy: Always
        args:
          ### make normal UI startup to connect via: oc rsh <pod-name> bash
          #- '--tail-log'
        ### checks that vnc server is up and running
        livenessProbe:
          tcpSocket:
            port: 5901
          initialDelaySeconds: 1
          timeoutSeconds: 1
        ### checks if http-vnc connection is working
        readinessProbe:
          httpGet:
            path: /
            port: 6901
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: jdk-mvn-py3-vnc
  name: jdk-mvn-py3-vnc
spec:
  externalName: jdk-mvn-py3-vnc
  ports:
  - name: http-port-tcp
    protocol: TCP
    port: 6901
    targetPort: 6901
    nodePort: 32001
  - name: vnc-port-tcp
    protocol: TCP
    port: 5901
    targetPort: 5901
    nodePort: 32002
  selector:
    application: jdk-mvn-py3-vnc
  type: NodePort
# Use type loadbalancer if needed
#  type: LoadBalancer
